project_id = "yudzgkrjsstqbfrrrrly"

[functions.virtual-tryon]
verify_jwt = false

[functions.generate-banner-image]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.image-analysis]
verify_jwt = false

[functions.pincode-lookup]
verify_jwt = false

[functions.sync-algolia]
verify_jwt = false

[functions.social-post-webhook]
verify_jwt = false

[functions.razorpay-create-order]
verify_jwt = false

[functions.razorpay-verify-payment]
verify_jwt = false

