project_id = "yudzgkrjsstqbfrrrrly"

[functions.virtual-tryon]
verify_jwt = false

[functions.generate-banner-image]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.image-analysis]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
